config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERPUSH: node
sqa_criteria:
  qc_doc:
    repos:
      this_repo:
        commands:
        - npm install
        container: node
timeout: 600
