config:
  credentials:
  - id: docker_hub_cred
    password_var: JPL_DOCKERPASS
    username_var: JPL_DOCKERUSER
  project_repos: {}
sqa_criteria:
  qc_doc:
    repos:
      this_repo:
        commands:
        - npm install
        container: sqaaas-web
timeout: 600
