services:
  sqaaas-web:
    build:
      args: {}
      context: ''
      dockerfile: .
    image: node
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
