services:
  sqaaas-web:
    container_name: "sqaaas-web"
    hostname: "sqaaas-web"
    build:
      context: .
    image: node
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
