services:
  sqaaas-web:
    build:
      context: .
    image: node
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
    command: sleep infinity
version: '3.7'
